keywords:
  "Intellectual Property":
    - "IP Development"
  "Internal Meetings":
    - "1:1 Slava:"
    - "Town hall"
    - "Braintrust"
    - "Educational"
    - "Benefits"
    - "Sync w"
    - "Beer"
    - "InfraMod"
  "OOO":
  "Goals":
    - "Goals"
  "Billable":
    - "EXT"
  "Management":
    - ":Slava"
    - "Management"
    - "Leadership"
    - "Resourcing"
    - "Team Building"
    - "Werewolf"
    - "Weekly G Cloud Ops"
allocations:
  "Intellectual Property": 0
  "Internal Meetings": 0
  "OOO": 0
  "Goals": 0
  "Billable": 0
  "Management": 0
