keywords:
  "Intellectual Property":
    - "IP"
  "Internal Meetings":
    - "1:1 Slava:"
    - "Town hall"
    - "Anthos On-Prem Biweekly"
    - "Braintrust"
    - "Educational Webinar"
    - "Benefits"
    - "Sync w"
    - "Beer"
    - "InfraMod"
  "OOO":
  "Goals":
    - "Goals"
  "Billable":
    - "Visby"
    - "Neustar"
    - "N*"
    - "CF"
    - "EPS"
    - "Governance"
  "Management":
    - ":Slava"
    - "Management"
    - "Resourcing"
    - "Team Building"
    - "Werewolf"
    - "Weekly G Cloud Ops"
allocations:
  "Intellectual Property": 0
  "Internal Meetings": 0
  "OOO": 0
  "Goals": 0
  "Billable": 0
  "Management": 0
